/**
 * @file AuditLog.ts
 * @description
 * Mongoose model definition for storing structured audit log records.
 *
 * This model represents the persistence layer of the audit logging system.
 * It defines how audit events are stored in MongoDB after being generated
 * by logging utilities such as:
 *
 * - `attachAuditLogging()` schema plugin
 * - `createErrorLogger()` error logging helper
 * - application-level logging functions
 *
 * ---------------------------------------------------------------------------
 * ARCHITECTURAL ROLE
 * ---------------------------------------------------------------------------
 * The `AuditLog` model serves as the central storage mechanism for
 * application activity tracking and observability.
 *
 * Typical use cases include:
 *
 * - Tracking CRUD operations across database models
 * - Recording user actions (account changes, role updates, etc.)
 * - Logging system errors and runtime exceptions
 * - Monitoring administrative actions
 * - Providing an audit trail for compliance or diagnostics
 *
 * The model is intentionally generic to allow it to be reused across
 * different types of events and application modules.
 *
 * ---------------------------------------------------------------------------
 * DESIGN PRINCIPLES
 * ---------------------------------------------------------------------------
 * - Minimal schema to maximize flexibility
 * - JSON-safe structured metadata storage
 * - Compatible with generic logging frameworks
 * - Optional user association
 * - Support for investigation workflows via resolution status
 *
 * ---------------------------------------------------------------------------
 * DOCUMENT FIELDS
 * ---------------------------------------------------------------------------
 *
 * action
 * ------
 * A semantic identifier describing the event that occurred.
 *
 * Example values:
 *
 * - `"user.account.created"`
 * - `"content.updated"`
 * - `"system.error"`
 * - `"payment.failed"`
 *
 * These identifiers should follow a consistent naming convention
 * across the application.
 *
 *
 * user
 * ----
 * MongoDB ObjectId referencing the user responsible for the event.
 *
 * This field may be `null` for system-generated events such as:
 *
 * - background jobs
 * - automated processes
 * - system-level errors
 *
 *
 * details
 * -------
 * Flexible JSON object containing structured metadata about the event.
 *
 * This field allows applications to store contextual information such as:
 *
 * - document identifiers
 * - operation parameters
 * - error stack traces
 * - external API responses
 *
 * Because the schema is intentionally flexible, this field should only
 * contain JSON-serializable values.
 *
 *
 * resolution
 * ----------
 * Indicates whether the logged event has been reviewed or resolved.
 *
 * Supported statuses are defined in `LOG_RESOULUTION_STATUS`.
 *
 * Typical values:
 *
 * - `"unresolved"`
 * - `"resolved"`
 * - `"under-review"`
 *
 * This field is particularly useful for:
 *
 * - incident management
 * - security monitoring
 * - administrative dashboards
 *
 *
 * createdAt
 * ---------
 * Timestamp indicating when the audit log entry was created.
 *
 * Automatically generated by Mongoose via schema timestamps.
 *
 * The schema intentionally disables `updatedAt` since audit logs are
 * designed to be immutable records of historical events.
 *
 * ---------------------------------------------------------------------------
 * INDEXING & PERFORMANCE NOTES
 * ---------------------------------------------------------------------------
 * For high-volume systems, consider adding indexes such as:
 *
 * - `{ action: 1 }`
 * - `{ user: 1 }`
 * - `{ createdAt: -1 }`
 *
 * These indexes improve performance for administrative dashboards
 * and log analysis queries.
 *
 * ---------------------------------------------------------------------------
 * SECURITY NOTES
 * ---------------------------------------------------------------------------
 * Sensitive information should never be stored in the `details` field.
 *
 * Avoid logging:
 *
 * - passwords
 * - authentication tokens
 * - API secrets
 * - private encryption keys
 *
 * Only store metadata necessary for auditing or debugging purposes.
 *
 * ---------------------------------------------------------------------------
 * @example
 * Creating a log entry manually
 *
 * ```ts
 * await AuditLog.create({
 *   action: "content.created",
 *   user: userId,
 *   details: {
 *     contentId: newContent._id,
 *     title: newContent.title
 *   }
 * });
 * ```
 *
 * ---------------------------------------------------------------------------
 * @example
 * Logging a system error
 *
 * ```ts
 * await AuditLog.create({
 *   action: "system.error",
 *   user: null,
 *   details: {
 *     context: "paymentWebhook",
 *     message: error.message
 *   }
 * });
 * ```
 *
 * ---------------------------------------------------------------------------
 * MODEL EXPORT BEHAVIOR
 * ---------------------------------------------------------------------------
 * The export pattern ensures that the model is not recompiled when the
 * code is executed multiple times in development environments such as:
 *
 * - Next.js
 * - serverless runtimes
 * - hot reload environments
 *
 * Mongoose caches models internally, so this pattern prevents the
 * "OverwriteModelError".
 */

import mongoose, { Schema } from "mongoose";
import { IAuditLog } from "../types/Logging";
import { LOG_RESOULUTION_STATUS } from "../constants/Logging";

const AuditLogSchema = new Schema<IAuditLog>(
  {
    action: { type: String, required: true },
    user: { type: Schema.Types.ObjectId, default: null },
    details: { type: Object, default: {} },
    resolution: {
      type: String,
      enum: LOG_RESOULUTION_STATUS,
      default: "unresolved"
    }
  },
  { timestamps: { createdAt: true, updatedAt: false } }
);

export default mongoose.models.AuditLog ||
  mongoose.model<IAuditLog>("AuditLog", AuditLogSchema);